site_name: 小安组文档库
nav:
  - Home: index.md
  - Contributors:
      - Contributors: CONTRIBUTORS.md
  - Contributing:
      - Contributing: CONTRIBUTING.md
      - GitHub Workflow:
          - GitHub Workflow: docs/github_workflow.md
theme: readthedocs